version: "3.3"

services:

  traefik:
    image: "traefik:v3.3"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.node.address=:3000"
    ports:
      - "80:80"
      - "8080:8080"
      - "3000:3000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

