http:
  routers:
    orchestration-router:
      rule: "Host(`api-orchestration.localhost`)" 
      service: api-orchestration-service
      entryPoints:
        - "web"
    orchestration-frontend:
      rule: "Host(`orchestration.localhost`)"
      service: orchestration-service
      entryPoints:
        - "web"

  services:
    api-orchestration-service:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:5000"
    orchestration-service:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3000"


