http:
  routers:
    orchestration-router:
      rule: "Host(`api-orchestration.dakshsangal.live`)"
      service: api-orchestration-service
      entryPoints:
        - "web"

    orchestration-frontend:
      rule: "Host(`orchestration.dakshsangal.live`)"
      service: orchestration-service
      entryPoints:
        - "web"

    orchestration-router-secure:
      rule: "Host(`api-orchestration.dakshsangal.live`)"
      service: api-orchestration-service
      entryPoints:
        - "websecure"
      tls:
        certResolver: letsencrypt

    orchestration-frontend-secure:
      rule: "Host(`orchestration.dakshsangal.live`)"
      service: orchestration-service
      entryPoints:
        - "websecure"
      tls:
        certResolver: letsencrypt

  services:
    api-orchestration-service:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:5000"
    orchestration-service:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3000"

