entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  dashboard: true
  insecure: true  

providers:
  docker:
    exposedByDefault: false
  file:
    filename: "/etc/traefik/rules.yml"
    watch: true
